Presentation/ITBlog.Presentation/Controllers/CategoryFolder/CategoryController.cs
using ITBlog.Business.CategoryServiceFolder;
using ITBlog.Business.DTO;
using ITBlog.Business.Enums;
using ITBlog.Business.PictureServiceFolder;
using ITBlog.Presentation.Models;
using Microsoft.AspNetCore.Mvc;

namespace ITBlog.Presentation.Controllers.CategoryFolder
{
    public class CategoryController : Controller
    {
        private readonly ICategoryService _categoryService;
        private readonly IPictureService _pictureService;

        public CategoryController(ICategoryService categoryService, IPictureService pictureService)
        {
            _categoryService = categoryService;
            _pictureService = pictureService;
        }

        public IActionResult Index(string seoName)
        {
            return View();
        }

        public PartialViewResult GetNavigationCategories()
        {
            var categories = _categoryService.GetCategoryByPlaceName(CateogryEnums.Navigation.ToString());

            if (categories == null || categories == default(Dictionary<CategoryDTO, List<CategoryDTO>>))
            {
                return PartialView();
            }

            return PartialView(categories);
        }

        [HttpGet(Name = "GetCategory/{Id}")]
        public IActionResult GetCategory(Guid Id)
        {
            if (Id == Guid.Empty)
            {
                return RedirectToAction("Error", "Home");
            }
            var model = new CategoryModel();
            var category = _categoryService.GetCategoryById(Id);

            if (category != null)
            {
                var posts = category.Posts.Select(x => x.Post).ToList();
                var tags = _categoryService.GetCategoryByPlaceName("Tag").Keys.ToList();
                var cv = _pictureService.GetCVByUserName("aytugeren");
                var popularPosts = posts.OrderBy(x => x.Comments.Count).ToList();
                var recentPosts = posts.OrderByDescending(x => x.CreatedDateTime).ToList();

                model.Posts = posts;
                model.CV = cv;
                model.Category = category;
                model.Tags = tags;
                model.PopularPostOfCategory = popularPosts;
                model.RecentPostOfCategory = recentPosts;

                return View(model);
            }

            return View();
        }
    }
}

Presentation/ITBlog.Presentation/Controllers/HomeFolder/SliderController.cs
using ITBlog.Business.Enums;
using ITBlog.Business.PictureServiceFolder;
using Microsoft.AspNetCore.Mvc;

namespace ITBlog.Presentation.Controllers.HomeFolder
{
    public class SliderController : Controller
    {
        private readonly IPictureService _pictureService;

        public SliderController(IPictureService pictureService)
        {
            _pictureService = pictureService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public PartialViewResult GetSliders()
        {
            var pictures = _pictureService.GetPicturesByPlaceName(PicturePlaceEnums.Slider.ToString());
            if (pictures != null)
            {
                return PartialView(pictures);
            }

            return PartialView();
        }
    }
}

Presentation/ITBlog.Presentation/Views/Shared/_Layout.cshtml
@using ITBlog.Presentation.Extensions
<!DOCTYPE html>
<html dir="ltr" lang="en-US">
<head>

	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="author" content="SemiColonWeb" />

	<!-- Stylesheets
	============================================= -->
	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,400i,700|Poppins:300,400,500,600,700|PT+Serif:400,400i&display=swap" rel="stylesheet" type="text/css" />
	<link rel="stylesheet" href="~/css/bootstrap.css" type="text/css" />
	<link rel="stylesheet" href="~/style.css" type="text/css" />
	<link rel="stylesheet" href="~/css/swiper.css" type="text/css" />
	<link rel="stylesheet" href="~/css/dark.css" type="text/css" />
	<link rel="stylesheet" href="~/css/font-icons.css" type="text/css" />
	<link rel="stylesheet" href="~/css/animate.css" type="text/css" />
	<link rel="stylesheet" href="~/css/magnific-popup.css" type="text/css" />

	<link rel="stylesheet" href="~/css/custom.css" type="text/css" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />

	<!-- Document Title
	============================================= -->
	<title>ITBlog</title>

</head>

<body class="stretched">
	<a href="#" class="btn btn-info me-2" style="display:none" id="infoAlert" data-notify-type="info" data-notify-msg="<i class='icon-info-sign me-1'></i> Welcome to Canvas Demo!" onclick="SEMICOLON.widget.notifications({ el: this }); return false;">Show Info</a>

	<a href="#" class="btn btn-danger me-2" style="display:none" id="errorAlert" data-notify-type="error" data-notify-msg="<i class='icon-remove-sign me-1'></i> Incorrect Input. Please Try Again!" onclick="SEMICOLON.widget.notifications({ el: this }); return false;">Show Error</a>

	<a href="#" class="btn btn-success me-2" style="display:none" id="successAlert" data-notify-type="success" data-notify-msg="<i class='icon-ok-sign me-1'></i> Message Sent Successfully!" onclick="SEMICOLON.widget.notifications({ el: this }); return false;">Show Success</a>

	<a href="#" class="btn btn-warning me-2" style="display:none" id="warningAlert" data-notify-type="warning" data-notify-msg="<i class='icon-warning-sign me-1'></i> Don't try to be too Smart!" onclick="SEMICOLON.widget.notifications({ el: this }); return false;">Show Warning</a>

	<!-- Document Wrapper
	============================================= -->
	<div id="wrapper" class="clearfix">

		<!-- Header
		============================================= -->
		<header id="header" class="header-size-sm">
			<div class="container">
				<div class="header-row">

					<!-- Logo
					============================================= -->
					<div id="logo" class="mx-auto">
						<a href="/" class="standard-logo" data-dark-logo="~/images/logo/2.png"><img src="~/images/logo/2.png" alt="Canvas Logo"></a>
					</div><!-- #logo end -->

				</div>
			</div>

			<div id="header-wrap" class="border-top border-f5">
				<div class="container">
					<div class="header-row justify-content-center">

						<div class="header-misc">

							<!-- Top Search
							============================================= -->
							<div id="top-search" class="header-misc-icon">
								<a href="#" id="top-search-trigger"><i class="icon-line-search"></i><i class="icon-line-cross"></i></a>
							</div><!-- #top-search end -->

						</div>

						<div id="primary-menu-trigger">
							<svg class="svg-trigger" viewBox="0 0 100 100"><path d="m 30,33 h 40 c 3.722839,0 7.5,3.126468 7.5,8.578427 0,5.451959 -2.727029,8.421573 -7.5,8.421573 h -20"></path><path d="m 30,50 h 40"></path><path d="m 70,67 h -40 c 0,0 -7.5,-0.802118 -7.5,-8.365747 0,-7.563629 7.5,-8.634253 7.5,-8.634253 h 20"></path></svg>
						</div>
						@await Html.RenderAction("GetNavigationCategories","Category")


						<form class="top-search-form" action="/Home/Search" method="get">
							<input type="text" name="SearchText" class="form-control" value="" placeholder="Arama.." autocomplete="off">
						</form>

					</div>

				</div>
			</div>
			<div class="header-wrap-clone"></div>
		</header><!-- #header end -->
		@await Html.RenderAction("GetSliders","Slider")


		<!-- Content
		============================================= -->
		<section id="content">
			<div class="content-wrap">
				<div class="container clearfix">

					@RenderBody()
				</div>
			</div>
		</section><!-- #content end -->
		@await Html.RenderAction("Footer","Home")


	</div><!-- #wrapper end -->
	<!-- Go To Top
	============================================= -->
	<div id="gotoTop" class="icon-angle-up"></div>

	<!-- JavaScripts
	============================================= -->
	<script src="~/js/jquery.js"></script>
	<script src="~/js/plugins.min.js"></script>

	<!-- Footer Scripts
	============================================= -->
	<script src="~/js/functions.js"></script>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Presentation/ITBlog.Presentation/Views/Shared/_LayoutAboutMe.cshtml
@using ITBlog.Presentation.Extensions
<!DOCTYPE html>
<html dir="ltr" lang="en-US">
<head>

	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="author" content="SemiColonWeb" />

	<!-- Stylesheets
	============================================= -->
	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,400i,700|Poppins:300,400,500,600,700|PT+Serif:400,400i&display=swap" rel="stylesheet" type="text/css" />
	<link rel="stylesheet" href="~/css/bootstrap.css" type="text/css" />
	<link rel="stylesheet" href="~/style.css" type="text/css" />
	<link rel="stylesheet" href="~/css/dark.css" type="text/css" />
	<link rel="stylesheet" href="~/css/font-icons.css" type="text/css" />
	<link rel="stylesheet" href="~/css/animate.css" type="text/css" />
	<link rel="stylesheet" href="~/css/magnific-popup.css" type="text/css" />

	<link rel="stylesheet" href="~/css/custom.css" type="text/css" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />


	<!-- Document Title
	============================================= -->
	<title>ITBlog</title>

</head>

<body class="stretched">
	@await Html.RenderAction("GetNavigationCategories","Category")

	<!-- Document Wrapper
	============================================= -->
	<div id="wrapper" class="clearfix">

		<!-- Page Title
		============================================= -->
		<section data-animate="fadeIn" id="page-title" class="page-title-parallax page-title-dark page-title-right include-header" style="padding: 350px 0; background-image: url('https://res.cloudinary.com/dndkzixum/image/upload/v1669654190/Content/Untitled_2000_1293_px_1_wfby2z.png');">

			<div class="container clearfix">
				<h1 data-animate="fadeIn" data-delay="1000">Nazım ÖZKAN</h1>
				<span data-animate="fadeIn" data-delay="2000">Software Developer</span>
			</div>

		</section><!-- #page-title end -->

		<!-- Content
		============================================= -->
		<section id="content">
			@RenderBody()
		</section><!-- #content end -->
	</div><!-- #wrapper end -->

	<!-- Go To Top
	============================================= -->
	<div id="gotoTop" class="icon-angle-up"></div>

	<!-- JavaScripts
	============================================= -->
	<script src="~/js/jquery.js"></script>
	<script src="~/js/plugins.min.js"></script>

	<!-- Footer Scripts
	============================================= -->
	<script src="~/js/functions.js"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Presentation/ITBlog.Presentation/Views/Shared/_LayoutLogin.cshtml
@using ITBlog.Presentation.Extensions
<!DOCTYPE html>
<html dir="ltr" lang="en-US">
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="author" content="SemiColonWeb" />

	<!-- Stylesheets
	============================================= -->
	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,400i,700|Poppins:300,400,500,600,700|PT+Serif:400,400i&display=swap" rel="stylesheet" type="text/css" />
	<link rel="stylesheet" href="~/css/bootstrap.css" type="text/css" />
	<link rel="stylesheet" href="~/style.css" type="text/css" />
	<link rel="stylesheet" href="~/css/dark.css" type="text/css" />
	<link rel="stylesheet" href="~/css/font-icons.css" type="text/css" />
	<link rel="stylesheet" href="~/css/animate.css" type="text/css" />
	<link rel="stylesheet" href="~/css/magnific-popup.css" type="text/css" />
	<link rel="stylesheet" href="~/css/components/datepicker.css" type="text/css" />
	<link rel="stylesheet" href="~/css/components/timepicker.css" type="text/css" />
	<link rel="stylesheet" href="~/css/components/daterangepicker.css" type="text/css" />
	<link rel="stylesheet" href="~/css/custom.css" type="text/css" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<!-- Document Title
	============================================= -->
	<title>Login</title>

</head>

<body class="stretched">
		<!-- Document Wrapper
	============================================= -->
	<div id="wrapper" class="clearfix">
		<a href="#" class="btn btn-info me-2" style="display:none" id="infoAlert" data-notify-type="info" data-notify-msg="<i class='icon-info-sign me-1'></i> Welcome to Canvas Demo!" onclick="SEMICOLON.widget.notifications({ el: this }); return false;">Show Info</a>

		<a href="#" class="btn btn-danger me-2" style="display:none" id="errorAlert" data-notify-type="error" data-notify-msg="<i class='icon-remove-sign me-1'></i> Incorrect Input. Please Try Again!" onclick="SEMICOLON.widget.notifications({ el: this }); return false;">Show Error</a>

		<a href="#" class="btn btn-success me-2" style="display:none" id="successAlert" data-notify-type="success" data-notify-msg="<i class='icon-ok-sign me-1'></i> Message Sent Successfully!" onclick="SEMICOLON.widget.notifications({ el: this }); return false;">Show Success</a>

		<a href="#" class="btn btn-warning me-2" style="display:none" id="warningAlert" data-notify-type="warning" data-notify-msg="<i class='icon-warning-sign me-1'></i> Don't try to be too Smart!" onclick="SEMICOLON.widget.notifications({ el: this }); return false;">Show Warning</a>

		<!-- Header
		============================================= -->
		<header id="header" class="full-header">
			<div id="header-wrap">
				<div class="container">
					<div class="header-row">
						<!-- Logo
						============================================= -->
						<div id="logo" class="mx-auto">
							<a href="/" class="standard-logo" data-dark-logo="~/images/logo/2.png"><img src="~/images/logo/2.png" alt="Canvas Logo"></a>
						</div><!-- #logo end -->

					</div>
				</div>
			</div>
		</header><!-- #header end -->

		<!-- Content
		============================================= -->
		<section id="content">
			<div class="content-wrap">
				<div class="container clearfix">

					<div class="tabs mx-auto mb-0 clearfix" id="tab-login-register" style="max-width: 500px;">
						@RenderBody()
					</div>

				</div>
			</div>
		</section><!-- #content end -->
	</div><!-- #wrapper end -->

	<!-- Go To Top
	============================================= -->
	<div id="gotoTop" class="icon-angle-up"></div>

	<!-- JavaScripts
	============================================= -->
	<script src="~/js/jquery.js"></script>
	<script src="~/js/plugins.min.js"></script>
	<!-- Date & Time Picker JS -->
	<script src="~/js/components/moment.js"></script>
	<script src="~/js/components/timepicker.js"></script>
	<script src="~/js/components/datepicker.js"></script>

	<!-- Include Date Range Picker -->
	<script src="~/js/components/daterangepicker.js"></script>
	<script>
		$(function () {
			$('.component-datepicker.default').datepicker({
				autoclose: true,
				startDate: "today",
			});

			$('.component-datepicker.today').datepicker({
				autoclose: true,
				startDate: "today",
				todayHighlight: true
			});

			$('.component-datepicker.past-enabled').datepicker({
				autoclose: true,
			});

			$('.component-datepicker.format').datepicker({
				autoclose: true,
				format: "dd-mm-yyyy",
			});

			$('.component-datepicker.autoclose').datepicker();

			$('.component-datepicker.disabled-week').datepicker({
				autoclose: true,
				daysOfWeekDisabled: "0"
			});

			$('.component-datepicker.highlighted-week').datepicker({
				autoclose: true,
				daysOfWeekHighlighted: "0"
			});

			$('.component-datepicker.mnth').datepicker({
				autoclose: true,
				minViewMode: 1,
				format: "mm/yy"
			});

			$('.component-datepicker.multidate').datepicker({
				multidate: true,
				multidateSeparator: " , "
			});

			$('.component-datepicker.input-daterange').datepicker({
				autoclose: true
			});

			$('.component-datepicker.inline-calendar').datepicker();

			$('.datetimepicker').datetimepicker({
				showClose: true
			});

			$('.datetimepicker1').datetimepicker({
				format: 'LT',
				showClose: true
			});

			$('.datetimepicker2').datetimepicker({
				inline: true,
				sideBySide: true
			});

			$('.datetimepicker3,.datetimepicker4').datetimepicker();

			// .daterange1
			$(".daterange1").daterangepicker({
				"buttonClasses": "button button-rounded button-mini m-0",
				"applyClass": "button-color",
				"cancelClass": "button-light"
			});

			// .daterange2
			$(".daterange2").daterangepicker({
				"opens": "center",
				timePicker: true,
				timePickerIncrement: 30,
				locale: {
					format: 'MM/DD/YYYY h:mm A'
				},
				"buttonClasses": "button button-rounded button-mini m-0",
				"applyClass": "button-color",
				"cancelClass": "button-light"
			});

			// .daterange3
			$(".daterange3").daterangepicker({
				singleDatePicker: true,
				showDropdowns: true
			},
				function (start, end, label) {
					var years = moment().diff(start, 'years');
					alert("You are " + years + " years old.");
				});

			// reportrange
			function cb(start, end) {
				$(".reportrange span").html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
			}
			cb(moment().subtract(29, 'days'), moment());

			$(".reportrange").daterangepicker({
				"buttonClasses": "button button-rounded button-mini m-0",
				"applyClass": "button-color",
				"cancelClass": "button-light",
				ranges: {
					'Today': [moment(), moment()],
					'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
					'Last 7 Days': [moment().subtract(6, 'days'), moment()],
					'Last 30 Days': [moment().subtract(29, 'days'), moment()],
					'This Month': [moment().startOf('month'), moment().endOf('month')],
					'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
				}
			}, cb);

			// .daterange4
			$(".daterange4").daterangepicker({
				autoUpdateInput: false,
				locale: {
					cancelLabel: 'Clear'
				},
				"buttonClasses": "button button-rounded button-mini m-0",
				"applyClass": "button-color",
				"cancelClass": "button-light"
			});

			$(".daterange4").on('apply.daterangepicker', function (ev, picker) {
				$(this).val(picker.startDate.format('MM/DD/YYYY') + ' - ' + picker.endDate.format('MM/DD/YYYY'));
			});

			$(".daterange4").on('cancel.daterangepicker', function (ev, picker) {
				$(this).val('');
			});

		});

	</script>
	<!-- Footer Scripts
	============================================= -->
	<script src="~/js/functions.js"></script>
	<script src="~/js/loginpage/loginandsignupjs.js"></script>

@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Presentation/ITBlog.Presentation/Views/Shared/_LayoutNone.cshtml
@using ITBlog.Presentation.Extensions
<!DOCTYPE html>
<html dir="ltr" lang="en-US">
<head>

	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="author" content="SemiColonWeb" />

	<!-- Stylesheets
	============================================= -->
	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,400i,700|Poppins:300,400,500,600,700|PT+Serif:400,400i&display=swap" rel="stylesheet" type="text/css" />
	<link rel="stylesheet" href="~/css/bootstrap.css" type="text/css" />
	<link rel="stylesheet" href="~/style.css" type="text/css" />
	<link rel="stylesheet" href="~/css/swiper.css" type="text/css" />
	<link rel="stylesheet" href="~/css/dark.css" type="text/css" />
	<link rel="stylesheet" href="~/css/font-icons.css" type="text/css" />
	<link rel="stylesheet" href="~/css/animate.css" type="text/css" />
	<link rel="stylesheet" href="~/css/magnific-popup.css" type="text/css" />

	<link rel="stylesheet" href="~/css/custom.css" type="text/css" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />

	<!-- Document Title
	============================================= -->
	<title>ITBlog</title>

</head>

<body class="stretched">
	<!-- Document Wrapper
	============================================= -->
	<div id="wrapper" class="clearfix">

		<!-- Content
		============================================= -->
		<section id="content">
			<div class="content-wrap">
				<div class="container clearfix">

					@RenderBody()
				</div>
			</div>
		</section><!-- #content end -->
	</div><!-- #wrapper end -->
	<!-- Go To Top
	============================================= -->
	<div id="gotoTop" class="icon-angle-up"></div>

	<!-- JavaScripts
	============================================= -->
	<script src="~/js/jquery.js"></script>
	<script src="~/js/plugins.min.js"></script>

	<!-- Footer Scripts
	============================================= -->
	<script src="~/js/functions.js"></script>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Presentation/ITBlog.Presentation/Views/Shared/_LayoutPostDetail.cshtml
@using ITBlog.Presentation.Extensions
<!DOCTYPE html>
<html dir="ltr" lang="en-US">
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="author" content="SemiColonWeb" />

	<!-- Stylesheets
	============================================= -->
	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,400i,700|Poppins:300,400,500,600,700|PT+Serif:400,400i&display=swap" rel="stylesheet" type="text/css" />
	<link rel="stylesheet" href="~/css/bootstrap.css" type="text/css" />
	<link rel="stylesheet" href="~/style.css" type="text/css" />
	<link rel="stylesheet" href="~/css/dark.css" type="text/css" />
	<link rel="stylesheet" href="~/css/font-icons.css" type="text/css" />
	<link rel="stylesheet" href="~/css/animate.css" type="text/css" />
	<link rel="stylesheet" href="~/css/magnific-popup.css" type="text/css" />

	<link rel="stylesheet" href="~/css/custom.css" type="text/css" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />

	<!-- Document Title
	============================================= -->
	<title>ITBlog</title>

</head>

<body class="stretched">
	<a href="#" class="btn btn-info me-2" style="display:none" id="infoAlert" data-notify-type="info" data-notify-msg="<i class='icon-info-sign me-1'></i> Welcome to Canvas Demo!" onclick="SEMICOLON.widget.notifications({ el: this }); return false;">Show Info</a>

	<a href="#" class="btn btn-danger me-2" style="display:none" id="errorAlert" data-notify-type="error" data-notify-msg="<i class='icon-remove-sign me-1'></i> Incorrect Input. Please Try Again!" onclick="SEMICOLON.widget.notifications({ el: this }); return false;">Show Error</a>

	<a href="#" class="btn btn-success me-2" style="display:none" id="successAlert" data-notify-type="success" data-notify-msg="<i class='icon-ok-sign me-1'></i> Message Sent Successfully!" onclick="SEMICOLON.widget.notifications({ el: this }); return false;">Show Success</a>

	<a href="#" class="btn btn-warning me-2" style="display:none" id="warningAlert" data-notify-type="warning" data-notify-msg="<i class='icon-warning-sign me-1'></i> Don't try to be too Smart!" onclick="SEMICOLON.widget.notifications({ el: this }); return false;">Show Warning</a>

	<!-- Document Wrapper
	============================================= -->
	<div id="wrapper" class="clearfix">

		<!-- Header
		============================================= -->
		<header id="header" class="header-size-sm">
			<div class="container">
				<div class="header-row">

					<!-- Logo
					============================================= -->
					<div id="logo" class="mx-auto">
						<a href="/" class="standard-logo" data-dark-logo="~/images/logo/2.png"><img src="~/images/logo/2.png" alt="Canvas Logo"></a>
					</div><!-- #logo end -->

				</div>
			</div>

			<div id="header-wrap" class="border-top border-f5">
				<div class="container">
					<div class="header-row justify-content-center">

						<div class="header-misc">

							<!-- Top Search
							============================================= -->
							<div id="top-search" class="header-misc-icon">
								<a href="#" id="top-search-trigger"><i class="icon-line-search"></i><i class="icon-line-cross"></i></a>
							</div><!-- #top-search end -->

						</div>

						<div id="primary-menu-trigger">
							<svg class="svg-trigger" viewBox="0 0 100 100"><path d="m 30,33 h 40 c 3.722839,0 7.5,3.126468 7.5,8.578427 0,5.451959 -2.727029,8.421573 -7.5,8.421573 h -20"></path><path d="m 30,50 h 40"></path><path d="m 70,67 h -40 c 0,0 -7.5,-0.802118 -7.5,-8.365747 0,-7.563629 7.5,-8.634253 7.5,-8.634253 h 20"></path></svg>
						</div>
						@await Html.RenderAction("GetNavigationCategories","Category")


						<form class="top-search-form" action="/Home/Search" method="get">
							<input type="text" name="SearchText" class="form-control" value="" placeholder="Arama.." autocomplete="off">
						</form>

					</div>

				</div>
			</div>
			<div class="header-wrap-clone"></div>
		</header><!-- #header end -->

		<!-- Content
		============================================= -->
		<section id="content">
			<div class="content-wrap">
				<div class="container clearfix">
					@RenderBody()
				</div>
			</div>
		</section><!-- #content end -->
		@await Html.RenderAction("Footer","Home")


	</div><!-- #wrapper end -->
	<!-- Go To Top
	============================================= -->
	<div id="gotoTop" class="icon-angle-up"></div>

	<!-- JavaScripts
	============================================= -->
	<script src="~/js/jquery.js"></script>
	<script src="~/js/plugins.min.js"></script>

	<!-- Footer Scripts
	============================================= -->
	<script src="~/js/functions.js"></script>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>